import { IDatePickerProperties } from '../../Interfaces/Component.Properties/IDatePicker.Properties';
import { IDateExtended } from '../../Interfaces/Data.Models/IDateExtended';
export declare class DatePicker {
    date: IDateExtended;
    private htmlMonthYearLabel;
    private htmlTextInput;
    private htmlElement;
    private htmlButtonInput;
    private htmlNextMonthButton;
    private htmlPreviousMonthButton;
    private htmlDatePicker;
    private daysTableCollection;
    private debouncedParseAndAddToOutput;
    private inputTxtClass;
    private inputsRowClass;
    private inputBtnClass;
    private monthSelectionClass;
    private buttonPreviousClass;
    private buttonNextClass;
    private monthDisplayClass;
    private dayLabelClass;
    private dayClass;
    private dayTableClass;
    private datePickerDivClass;
    private todayClass;
    private selectedDayClass;
    private showDateOnStart;
    constructor(properties: IDatePickerProperties, date: IDateExtended);
    changeValue(operation: string, value?: any): any;
    private nextMonth;
    private previousMonth;
    private fillMonthYearLabel;
    private setProperties;
    private setHTMLElementsAndCollections;
    private fillDayLabels;
    private fillElementWithValues;
    private fillElementWithEmptyValues;
    private fillDays;
    private removeDayClasses;
    private setTodayAndSelectedDayClass;
    private addDayEventHandler;
    private createHTMLElements;
    private createInputsRow;
    private createDatePickerElem;
    private createMonthSelectionElement;
    private createDaysTable;
    private createDays;
    private createDaysLabels;
}
